#ifndef SYSTYPE_H
#define SYSTYPE_H
namespace ecs {

	enum TypeSystem {

		TYPEBUTTONSYSTEM,
		TYPELOGICSYSTEM,
		TYPETRANSFORMSYSTEM,
		TYPEPHYSICSSYSTEM,
		TYPECOLLISIONSYSTEM,
		TYPECOLLISIONRESPONSESYSTEM,



		TYPERAYCASTSYSTEM,
		TYPEPATHFINDINGSYSTEM,


		TYPEAUDIOSYSTEM,

		//render system called the last
		TYPEANIMATIONSYSTEM,
		TYPERENDERSYSTEM,
		TYPELIGHTINGSYSTEM,
		TYPEUIRENDERSYSTEM,
		TYPERENDERTEXTSYSTEM,
		TYPEDEBUGDRAWINGSYSTEM,
		TYPECAMERASYSTEM,
		TYPETILEMAPSYSTEM,
		
		TYPEVIDEOSYSTEM,
		
		TYPEGRIDSYSTEM,
		TYPEPARTICLESYSTEM,
		TOTALTYPESYSTEM
	};
}

#endif